version: "3"
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password   # Contraseña para el usuario root
      MYSQL_DATABASE: BdIntegrador          # Nombre de la base de datos a crear
      MYSQL_USER: IntegradorUser            # Nombre del usuario que deseas crear
      MYSQL_PASSWORD: password              # Contraseña para el usuario creado
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: